---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Copy shell script to remote server
      ansible.builtin.template:
        src: "files/agent.j2"
        dest: "/tmp/agent.sh"
      
    - name: Run shell script on remote server
      ansible.builtin.shell:
        shell: sh /tmp/agent.sh
<<<<<<< HEAD
=======
        
    
>>>>>>> 6e34adf (last update)
